"""Sandboxed web agent — the public face of the website.

SECURITY BOUNDARY: This agent is completely isolated from the
internal AgentLoop.  It has:
  - Access to a cloud LLM backend (for conversation only)
  - Its own system prompt (lead-gen focused, no tool instructions)
  - Its own per-session conversation history (in-memory, ephemeral)
  - ZERO access to: tools, memory stores, Jira, email, calendar,
    Cursor, file system, knowledge base, or any internal state.

Web visitors interact with this agent.  The internal AgentLoop is
never exposed to public traffic.
"""

from __future__ import annotations

import logging
import time
from collections import defaultdict
from dataclasses import dataclass, field
from typing import AsyncIterator

from palmtop.inference.base import InferenceBackend, Message
from palmtop.web.sanitize import sanitize_input, sanitize_output

log = logging.getLogger(__name__)

# Hard caps
MAX_HISTORY_TURNS = 20       # per session — prevents memory exhaustion
MAX_INPUT_LENGTH = 1000      # chars per message
MAX_MESSAGES_PER_SESSION = 30  # hard cap — after this, ask for email
SESSION_TTL = 3600 * 4       # 4 hours — then session history is purged


# WEB_SYSTEM_PROMPT is now generated by persona.build_web_system_prompt()
# and passed to WebAgent.__init__ via the system_prompt parameter.


@dataclass
class _Session:
    """Ephemeral per-visitor conversation state."""
    history: list[Message] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)
    last_active: float = field(default_factory=time.time)
    message_count: int = 0


class WebAgent:
    """Sandboxed conversational agent for website visitors.

    Uses the cloud LLM for inference but has NO access to tools,
    memory stores, or any internal systems.
    """

    def __init__(self, llm: InferenceBackend, system_prompt: str = "") -> None:
        self._llm = llm
        self._system_prompt = system_prompt
        self._sessions: dict[str, _Session] = {}

    async def handle(self, text: str, session_id: str) -> str:
        """Handle a visitor message and return a reply."""
        # Sanitize input
        clean = sanitize_input(text, MAX_INPUT_LENGTH)
        if not clean:
            return "Could you say that again?  I didn't quite catch it."

        session = self._get_or_create_session(session_id)
        session.last_active = time.time()
        session.message_count += 1

        # Hard cap: after N messages, stop generating LLM replies
        if session.message_count > MAX_MESSAGES_PER_SESSION:
            return (
                "Hey — we've been chatting for a while!  To keep the "
                "conversation going properly, drop your email in the "
                "form below and we'll pick up right where we left off."
            )

        # Build message list
        messages = [Message(role="system", content=self._system_prompt)]
        messages.extend(session.history)
        messages.append(Message(role="user", content=clean))

        # Generate reply
        try:
            raw_reply = await self._llm.complete(messages, max_tokens=600)
        except Exception:
            log.exception("WebAgent LLM error for session %s", session_id[:8])
            return (
                "Apologies — I hit a temporary issue on my end.  "
                "Try again in a moment, or drop your email and "
                "we'll reach out directly."
            )

        reply = sanitize_output(raw_reply)

        # Update history (capped)
        session.history.append(Message(role="user", content=clean))
        session.history.append(Message(role="assistant", content=reply))
        if len(session.history) > MAX_HISTORY_TURNS * 2:
            # Keep the most recent turns
            session.history = session.history[-(MAX_HISTORY_TURNS * 2):]

        return reply

    async def handle_stream(
        self, text: str, session_id: str
    ) -> AsyncIterator[tuple[str, str]]:
        """Yield (event, data) tuples for SSE streaming.

        For Phase 1 this wraps handle() in a single done event.
        Phase 2 can add true token streaming if the LLM backend supports it.
        """
        yield ("status", "thinking")
        reply = await self.handle(text, session_id)
        yield ("done", reply)

    def _get_or_create_session(self, session_id: str) -> _Session:
        now = time.time()
        session = self._sessions.get(session_id)
        if session and (now - session.created_at) > SESSION_TTL:
            # Expired — start fresh
            del self._sessions[session_id]
            session = None
        if session is None:
            session = _Session()
            self._sessions[session_id] = session
        return session

    def cleanup_expired(self) -> int:
        """Remove expired sessions.  Call periodically from a background task."""
        now = time.time()
        expired = [
            sid for sid, s in self._sessions.items()
            if (now - s.created_at) > SESSION_TTL
        ]
        for sid in expired:
            del self._sessions[sid]
        if expired:
            log.info("Cleaned up %d expired web sessions", len(expired))
        return len(expired)

    @property
    def active_sessions(self) -> int:
        return len(self._sessions)
